trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  project: 'Itan.Database/Itan.Database.csproj'

steps:
  - task: AzureKeyVault@1
    displayName: Fetch AKV
    inputs:
      azureSubscription: 'payg_itan_service_connection'
      KeyVaultName: 'itan-key-vault'
      SecretsFilter: '*'
      RunAsPreJob: false
  - task: UseDotNet@2
    displayName: Use .net Core SDK 7
    inputs:
      packageType: sdk
      version: 7.x
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      projects: '$(project)'
  
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: build
      projects: '$(project)'

  - task: DotNetCoreCLI@2
    inputs:
        command: 'custom'
        custom: 'tool'
        arguments: 'install --global dotnet-ef'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'PAYG (itan) service connection'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: 'dotnet ef migrations script -i -o migration.sql'
      workingDirectory: 'Itan.Database'

  - task: AzureCLI@2
    inputs:
      azureSubscription:  'PAYG (itan) service connection'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: 'dotnet ef migrations list --project $(project) --startup-project $(project) --msbuildprojectextensionspath Itan.Database/obj/local'
  - task: AzureCLI@2
    inputs:
      azureSubscription:  'PAYG (itan) service connection'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: 'dotnet ef migrations script -i -o $(Build.ArtifactStagingDirectory)/migration.sql --project $(project) --startup-project $(project) --msbuildprojectextensionspath obj/local'
 
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'migration-sql-file'
      publishLocation: 'Container'


